name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: |
        cd server
        ./mvnw --batch-mode --update-snapshots deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Archifacts/spring-restbucks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
